--- 
title: "Cartographie avec R à l'usage des statisticiens"
author: "Thomas Vroylandt"
date: "7 février 2020"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
github-repo: tvroylandt/r-cartostat
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction {-}

Ce support a été rédigé par Thomas Vroylandt, statisticien au sein de la Direction des Statistiques, des Etudes et de l'Evaluation de Pôle emploi.

## Objectifs {-}

Ce guide vise à :

+ introduire quelques notions sur les données spatiales ;
+ permettre de représenter des valeurs sous forme de cartes par aplats de couleurs ;
+ permettre de représenter des valeurs sous forme de cartes à ronds proportionnels ;
+ personnaliser ces cartes ;
+ exporter les résultats pour publication.

## Ressources {-}

Ces ressources ont servis à construire ce support :

+ Le support de cours réalisé par Maël Theulière a été une grande référence. La partie sur les projets dans R est en tirée : https://maeltheuliere.github.io/rspatial/ ;
+ Tout savoir sur le spatial avec R : https://geocompr.robinlovelace.net/ ;
+ La ressource sur les recodages et le maniement des données : [https://r4ds.had.co.nz/](https://r4ds.had.co.nz/) (en anglais) ;
+ Une bonne introduction, qui a notamment servie pour la partie recodages : [https://juba.github.io/tidyverse/](https://juba.github.io/tidyverse/) (en français).

## Exercices {-}

Les données sont disponibles dans le dossier Github https://github.com/tvroylandt/r-cartostat.

La feuille d'exercice est ici : https://tvroylandt.github.io/r-cartostat/feuille_exos.html

La feuille corrigée ici : https://tvroylandt.github.io/r-cartostat/feuille_exos_correction.html

## Licence {-}

Ce document est sous licence Creative Commons BY-NC-SA : http://creativecommons.org/licenses/by-nc-sa/4.0/